{{- range $cluster := .Values.clusters }}
{{ if not .disable }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $cluster.name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: {{ $.Values.global.project }}
  source:
    path: cluster/
    repoURL: {{ $.Values.global.repoURL }}
    revision: {{ $.Values.global.revision }}
    helm:
      parameters:
      {{- range $name, $val := $cluster }}
      - name: {{ $name }}
        value: {{ $val }}
      {{- end }}
      values: |-
        global:
          {{- range $name, $val := $.Values.global }}
          {{ $name }}: {{ $val | quote }}
          {{- end }}
        cluster:
          {{- range $name, $val := $cluster }}
          {{ $name }}: {{ $val | quote }}
          {{- end }}
---
{{- end }}
{{- end }}