apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: cluster/
    repoURL: https://github.com/t6iz8t48/argo-apps.git
    targetRevision: HEAD
