apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd-apps-test
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: deployment.replicaCount
        value: "1"
      - name: message
        value: This is a test of app-of-apps-of-apps
    path: deploy/helm/hello-kubernetes
    repoURL: https://github.com/paulbouwer/hello-kubernetes
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true