apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster.name }}-hello-world
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd-apps-test
    server: {{ .Values.global.server }}
  project: default
  source:
    path: deploy/helm/hello-kubernetes
    repoURL: https://github.com/paulbouwer/hello-kubernetes
    targetRevision: HEAD
    helm:
      parameters:
      - name: deployment.replicaCount
        value: "1"
      - name: message
        value: "Hello world from {{ .Values.cluster.name }}"
